# Generated by Django 6.0.4 on 2026-04-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_post_platform_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notified_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='notified_due',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform',
            field=models.CharField(choices=[('General', 'General'), ('X', 'X'), ('LinkedIn', 'LinkedIn'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook')], default='General', max_length=50),
        ),
    ]
